version: "3.7"
services:
  server:
    image: adguard/adguardhome:latest
    volumes:
    - data:/opt/adguardhome/work
    - config:/opt/adguardhome/conf
    ports:
    - 3000:3000/tcp
    - 53:53/tcp
    - 53:53/udp
    - 80:80/tcp
    - 443:443/tcp
    - 443:443/udp
    - 853:853/tcp
    - 853:853/udp
    - 784:784/udp
volumes:
  data:
  config:
