version: "3.7"
services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: #- Mot de passe root de la base de données
      MYSQL_USER: #- Nom d'utilisateur de la base de données
      MYSQL_PASSWORD: #- Mot de passe de l'utilisateur de la base de données
      MYSQL_DATABASE: gitea
    volumes:
    - ./database:/var/lib/mysql
  server:
    image: gitea/gitea:latest
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: database:3306
      GITEA__database__NAME: gitea
      GITEA__database__USER: #- Nom d'utilisateur de la base de données
      GITEA__database__PASSWD: #- Mot de passe de l'utilisateur de la base de données
    volumes:
    - ./data:/data
    ports:
    - "3000:3000"
    - "22:22"
