version: "3.7"
services:
  server:
    image: b4bz/homer:latest
    volumes:
    - ./data:/www/assets
    environment:
      #INIT_ASSETS: 0 # A utiliser après le premier lancement
    ports:
    - "8080:8080"
