version: "3.7"
services:
  server:
    image: linuxserver/jellyfin:latest
    volumes:
    - ./config:/config
    - ./data:/data
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Paris
    ports:
    - "8096:8096"
    - "8920:8920"
    - "7359:7359/udp"
    - "1900:1900/udp"
