version: "3.7"
services:
  server:
    image: docker.n8n.io/n8nio/n8n
    ports:
    - 5678:5678/tcp
    environment:
      NODE_ENV: production
      N8N_HOST: ${SUBDOMAIN}.${DOMAIN_NAME}
      WEBHOOK_URL: https://${SUBDOMAIN}.${DOMAIN_NAME}/
      GENERIC_TIMEZONE: Europe/Paris
    volumes:
    - data:/home/node/.n8n
volumes:
  data:
