version: "3.7"
services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: #- Mot de passe root de la base de données
      MYSQL_USER: #- Nom d'utilisateur de la base de données
      MYSQL_PASSWORD: #- Mot de passe de l'utilisateur de la base de données
      MYSQL_DATABASE: nextcloud
    volumes:
    - database:/var/lib/mysql
  server:
    image: nextcloud:latest
    volumes:
    - data:/var/www/html
    environment:
      MYSQL_HOST: database:3306
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: #- Nom d'utilisateur de la base de données
      MYSQL_PASSWORD: #- Mot de passe de l'utilisateur de la base de données
    ports:
    - 8080:80
volumes:
  database:
  data:
